### ISSUE TITLE
How does the #ID field work?

### ISSUE THREAD

**Issue by darth-donut** [zhangwei2015/IMonitor#1]
In *.structure.gz file, the first field #ID has values cp*.
Initially, I've assumed that since all values of cp starts from cp1 .. n, cp1 implies first read and cpN implies the Nth read.

However, there's a point in the file where cpN actually means N-1th read, and another point in the file where cpN implies the N+1th read. I got to know this because I had a reference file, where I can compare the VDJ and CDR3 assignments.

Question is, how does the #ID field work? The numbers don't work as I think they do.

Cheers,
Harry

**Comment by zhangwei2015** [comment]
Dear Harry,

In .structure.gz file, the first field #ID has values cp.
cp# , starts from cp1..n, cp1 implies first read and cpN implies the Nth read. For example, if you have 1000 (paired-end) reads, the #ID will be cp1,...,cp1000.

Actually, you can check the file "*.change_id.backup.gz"(in the Result directory) to find the relationship between raw reads ID and the new ID(cp#). 

If you still have some problems, please let me know!

Best Regards!
Wei

**Comment by darth-donut** [comment]
I see, I'll look at *.change-id.backup.gz for the ids then. Because my initial assumtion was true, as you've confirmed that cpN implies Nth read, but using my reference data, it seems like at some point, it switches to N+1 (i.e. cp1000 was actually the 1001th read), and later on N+2. I have yet to see N+3, but it might be because my data isn't large enough (there were 500k reads).
